version: '3.8'

services:

  captcha:
    build:
      context: .
    command: python manage.py runserver 0.0.0.0:80

  tests_browser:
    build:
      context: ./tests/browser
    entrypoint: node
    command: test.js
    depends_on:
      - captcha
